import fs from "node:fs";
import path from "node:path";
import { getContentRoot, loadCollection } from "../src/content-utils.mjs";

const dist = path.resolve(process.cwd(), "dist");
const contentRoot = getContentRoot();

fs.rmSync(dist, { recursive: true, force: true });
fs.mkdirSync(dist, { recursive: true });

const basePages = [
  ["index.html", "Home"],
  ["leaderboard/index.html", "Leaderboard"],
  ["blog/index.html", "Blog"],
  ["changelog/index.html", "Changelog"],
  ["rules/index.html", "Rules"],
  ["404.html", "Not Found"]
];
for (const [rel, title] of basePages) {
  writePage(path.join(dist, rel), `<h1>${title}</h1><p>Generated by ks-home build.</p>`);
}

for (const entry of loadCollection(contentRoot, "blog")) {
  writePage(path.join(dist, "blog", entry.metadata.slug, "index.html"), `<h1>${entry.metadata.title}</h1>`);
}
for (const entry of loadCollection(contentRoot, "changelog")) {
  writePage(path.join(dist, "changelog", entry.metadata.slug, "index.html"), `<h1>${entry.metadata.title}</h1>`);
}

function writePage(filePath, body) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(
    filePath,
    `<!doctype html><html lang="en"><body><header></header><main>${body}</main><footer></footer></body></html>`,
    "utf8"
  );
}

console.log("build complete: static foundation generated");
